"""Generate the synthetic-PII overlay and issue labeled Article-17 erasure requests.

This module originally rendered all 100 fake employees as one shared
"Team Directory" markdown page/doc (`LEGACY_TEAM_DIRECTORY_DOC_ID` below).
That was a modeling mistake: the ledger's erasure_requests table is
doc_id-keyed, and the generic recursive chunker doesn't align chunk
boundaries to individual table rows (its hard-split fallback slices by raw
token offset, so employee rows could straddle - or even split across -
chunk boundaries).

SYNTHETIC DATA ONLY: every record here is generated by Faker from
seeds.MASTER_SEED=42. None of it is real personal data. Every rendered page
and manifest entry is labeled as synthetic so it can never be mistaken for
an actual GitLab employee record.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

from faker import Faker

import seeds
from corpus import clean as clean_mod
from corpus import ingest_baseline
from engines import chroma_adapter, pgvector_adapter, qdrant_adapter
from ledger import ledger

N_SYNTHETIC_EMPLOYEES = 100

LEGACY_TEAM_DIRECTORY_DOC_ID = "synthetic-pii/team-directory"

DOC_ID_PREFIX = "synthetic-pii/employee"


def employee_doc_id(employee_id: str) -> str:
    return f"{DOC_ID_PREFIX}/{employee_id}"


@dataclass
class FakeEmployee:
    employee_id: str
    name: str
    title: str
    department: str
    location: str
    email: str
    start_date: str
    doc_id: str | None = None
    chunk_id: str | None = None


DEPARTMENTS = [
    "Engineering",
    "Product",
    "People Ops",
    "Marketing",
    "Sales",
    "Finance",
    "Security",
    "Customer Support",
]


def generate_fake_employees(n: int = N_SYNTHETIC_EMPLOYEES, seed: int = seeds.MASTER_SEED) -> list[FakeEmployee]:
    seeds.seed_everything(seed)
    fake = Faker()
    Faker.seed(seed)

    employees = []
    for i in range(n):
        name = fake.name()
        department = fake.random_element(DEPARTMENTS)
        employee_id = f"SYN-{i + 1:04d}"
        employees.append(
            FakeEmployee(
                employee_id=employee_id,
                name=name,
                title=fake.job(),
                department=department,
                location=fake.city(),
                email=fake.unique.email(),
                start_date=fake.date_between(start_date="-5y", end_date="today").isoformat(),
                doc_id=employee_doc_id(employee_id),
            )
        )
    return employees


def render_employee_profile_md(employee: FakeEmployee) -> str:
    """One small standalone "profile" page per employee- deliberately NOT a
    shared table, so the generic chunker (paragraph-packed, well under
    max_tokens) always produces exactly one chunk per employee, giving exact
    employee<->chunk identity for the erasure demo."""
    lines = [
        "---",
        f"title: {employee.name} (synthetic)",
        "---",
        "",
        "> **SYNTHETIC DATA NOTICE:** this profile is fake, generated with",
        "> [Faker](https://faker.readthedocs.io/) (seed=42) for the rag-index-decay",
        "> GDPR-erasure teardown. This is not a real GitLab employee or real personal",
        "> data. See `results/synthetic_pii_manifest.json` for the full labeled manifest.",
        "",
        f"# {employee.name} (synthetic)",
        "",
        f"- **Employee ID:** {employee.employee_id}",
        f"- **Title:** {employee.title}",
        f"- **Department:** {employee.department}",
        f"- **Location:** {employee.location}",
        f"- **Email:** {employee.email}",
        f"- **Start date:** {employee.start_date}",
        "",
    ]
    return "\n".join(lines)


def write_manifest(employees: list[FakeEmployee], path: str | Path = "results/synthetic_pii_manifest.json") -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "notice": "SYNTHETIC DATA ONLY - generated with Faker, seed=42. Not real personal data.",
        "doc_id_prefix": DOC_ID_PREFIX,
        "count": len(employees),
        "employees": [asdict(e) for e in employees],
    }
    path.write_text(json.dumps(payload, indent=2))
    return path


def migrate_pii_overlay_to_per_employee(conn, tokenizer, t0_sha: str, t0_date: str) -> dict:
    """Replace the legacy single Team Directory doc with
    100 separate per-employee docs (one chunk each). Idempotent - if the
    per-employee docs already exist, this is a no-op.

    Purges the legacy doc's chunks from the ledger AND all 3 live engines
    (this is a real, deliberate fix, not a modeled churn/failure event -
    unlike churn/replay.py's failure-mode deletes, this always waits for a
    fully-consistent delete)."""
    if ledger.get_document_status(conn, employee_doc_id("SYN-0001")) is not None:
        return {"skipped": True, "reason": "already migrated"}

    legacy_chunk_ids = ledger.chunk_ids_for_doc(conn, LEGACY_TEAM_DIRECTORY_DOC_ID)

    pg_conn = pgvector_adapter.get_conn()
    pgvector_adapter.ensure_schema(pg_conn)
    qd_client = qdrant_adapter.get_client()
    qdrant_adapter.ensure_collection(qd_client)
    ch_client = chroma_adapter.get_client()
    ch_coll = chroma_adapter.ensure_collection(ch_client)

    for cid in legacy_chunk_ids:
        pgvector_adapter.delete_by_chunk_id(pg_conn, cid)
        qdrant_adapter.delete_by_chunk_id(qd_client, cid)
        chroma_adapter.delete_by_chunk_id(ch_coll, cid)
    ledger.purge_document(conn, LEGACY_TEAM_DIRECTORY_DOC_ID)
    conn.commit()

    employees = generate_fake_employees()  # same seed=42 -> identical 100 records as before

    chunk_records: list[tuple[str, str]] = []
    for emp in employees:
        raw_md = render_employee_profile_md(emp)
        cleaned = clean_mod.clean_text(raw_md, f"synthetic:employee/{emp.employee_id}.md")
        assert cleaned is not None, f"synthetic employee profile {emp.employee_id} was treated as a stub"
        _version_id, records = ingest_baseline.ingest_doc_version(
            conn, emp.doc_id, cleaned.source_path, cleaned.body, t0_sha, t0_date, tokenizer,
            action="add", status="live", is_synthetic_pii=1,
        )
        assert len(records) == 1, f"expected exactly 1 chunk for {emp.doc_id}, got {len(records)}"
        emp.chunk_id = records[0][0]
        chunk_records.extend(records)
    conn.commit()

    embeddings = ingest_baseline.embed_all(chunk_records)
    pairs = [(cid, embeddings[cid]) for cid, _ in chunk_records]
    pgvector_adapter.upsert(pg_conn, pairs)
    qdrant_adapter.upsert(qd_client, pairs)
    chroma_adapter.upsert(ch_coll, pairs)

    applied_at = datetime.now(timezone.utc).isoformat()
    for engine_name in ingest_baseline.ENGINES:
        rows = [(engine_name, cid, "upsert", applied_at, t0_sha, 1) for cid, _ in pairs]
        ledger.insert_index_events(conn, rows)
    conn.commit()

    write_manifest(employees)

    return {
        "skipped": False,
        "applied_at": applied_at,
        "legacy_doc_id": LEGACY_TEAM_DIRECTORY_DOC_ID,
        "legacy_chunks_removed": len(legacy_chunk_ids),
        "new_employee_docs_added": len(employees),
        "new_employee_chunks_added": len(pairs),
        "pg_conn": pg_conn,
        "qd_client": qd_client,
        "ch_coll": ch_coll,
    }


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Synthetic PII overlay: generate/migrate the per-employee doc set")
    parser.add_argument(
        "--migrate", action="store_true",
        help="Purge the legacy Team Directory doc, "
             "re-ingest 100 per-employee docs.",
    )
    args = parser.parse_args()

    if args.migrate:
        from corpus import acquire as acquire_mod
        from corpus import chunk as chunk_mod

        t0 = acquire_mod.acquire()
        conn = ledger.init_db(ingest_baseline.LEDGER_PATH)
        tokenizer = chunk_mod.get_tokenizer()
        result = migrate_pii_overlay_to_per_employee(conn, tokenizer, t0["sha"], t0["commit_date"])
        print(json.dumps({k: v for k, v in result.items() if k not in ("pg_conn", "qd_client", "ch_coll")}, indent=2))
    else:
        emps = generate_fake_employees()
        print(render_employee_profile_md(emps[0])[:500])
        write_manifest(emps)
